name: Roboto
on: [pull_request]

jobs:

  build:
    name: Build Roboto
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          # TODO use build matrix?
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
              ${{ runner.os }}-pip-

      - name: Build fonts
        run: sh sources/build.sh

      - name: Upload fonts
        uses: actions/upload-artifact@v1
        with:
          name: fonts
          path: fonts/

  test:
    name: Test Roboto
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download fonts
        uses: actions/download-artifact@v1
        with:
          name: fonts

      - name: Test fonts
        run: fontbakery check-profile tests/test_general.py fonts/unhinted/Roboto[ital,wdth,wght].ttf

